repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0  # Use the ref you want to point at
    hooks:
      - id: fix-encoding-pragma