# pip install travis-encrypt

language: python
env:
  - INSTALL_ON_LINUX=1
python:
  - "3.9"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -c "pass"
deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  on:
    branch: master